name: isweep
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - python>=3.7
  - numpy>=1.21
  - pandas
  - scipy>=1.7
  - matplotlib
  - seaborn
  - networkx
  - tskit
  - pyslim
  - tszip
  - msprime
  - stdpopsim
  - snakemake
  - jupyter
  - notebook
  - pip
  - pip:
      - isweep
  - r-base
  - r-essentials
  - bcftools
# if issues with bcftools: (https://github.com/alek0991/iSAFE/issues/17)
# use separate isafe environment for simulation study
